name: Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: weeklytrainingemail
  REGION: europe-southwest1
  REPO_NAME: mis-imagenes
  IMAGE_NAME: mi-imagen

jobs:
  build-push-gcr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Autenticaci√≥n segura mediante Workload Identity Federation
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/1051676200850/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-deploy@weeklytrainingemail.iam.gserviceaccount.com'

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest .
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
